export const FULL_SYMPTOMS_LIST = [
  { value: "fatigue", label: "Fatigue" },
  { value: "bouffees_chaleur", label: "Bouffées de chaleur" },
  { value: "insomnie", label: "Insomnie" },
  { value: "sautes_humeur", label: "Sautes d'humeur" },
  { value: "prise_de_poids", label: "Prise de poids" },
  { value: "secheresse_cutanee", label: "Sécheresse cutanée" },
  { value: "douleurs_articulaires", label: "Douleurs articulaires" },
  { value: "brain_fog", label: "Troubles de la mémoire" },
  { value: "anxiete", label: "Anxiété" },
  { value: "baisse_libido", label: "Baisse de libido" },
  { value: "maux_de_tete", label: "Maux de tête" },
  { value: "palpitations", label: "Palpitations" },
  { value: "ballonnements", label: "Ballonnements" },
  { value: "irritabilite", label: "Irritabilité" },
  { value: "deprime", label: "Déprime / mélancolie" },
  { value: "transpiration_nocturne", label: "Transpiration nocturne" },
  { value: "fragilite_ongles_cheveux", label: "Fragilité ongles et cheveux" },
  { value: "secheresse_vaginale", label: "Sécheresse vaginale" },
];
