// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-food-logs.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_food_logs_default = defineTool({
  name: "list_food_logs",
  title: "Lister les repas logg\xE9s",
  description: "Liste les aliments enregistr\xE9s dans le journal de l'utilisatrice pour une plage de dates (d\xE9faut: 7 derniers jours).",
  inputSchema: {
    from: z.string().describe("Date de d\xE9but YYYY-MM-DD (incluse). Optionnel.").optional(),
    to: z.string().describe("Date de fin YYYY-MM-DD (incluse). Optionnel.").optional(),
    limit: z.number().int().describe("Nombre max de lignes (d\xE9faut 100).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("food_logs").select("id, food_name, meal_type, portion_size, calories, proteins, carbs, fats, logged_at").order("logged_at", { ascending: false }).limit(limit ?? 100);
    if (from) q = q.gte("logged_at", from);
    if (to) q = q.lte("logged_at", to + "T23:59:59");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-food.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_food_default = defineTool2({
  name: "log_food",
  title: "Ajouter un aliment au journal",
  description: "Enregistre un aliment dans le journal alimentaire de l'utilisatrice avec ses macros optionnelles.",
  inputSchema: {
    food_name: z2.string().describe("Nom de l'aliment."),
    portion_size: z2.number().describe("Quantit\xE9 en grammes ou ml.").optional(),
    meal_type: z2.enum(["petit_dejeuner", "dejeuner", "diner", "collation"]).describe("Type de repas.").optional(),
    calories: z2.number().optional(),
    proteins: z2.number().optional(),
    carbs: z2.number().optional(),
    fats: z2.number().optional(),
    logged_at: z2.string().describe("ISO date. D\xE9faut: maintenant.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("food_logs").insert({
      user_id: ctx.getUserId(),
      food_name: input.food_name,
      portion_size: input.portion_size ?? null,
      meal_type: input.meal_type ?? null,
      calories: input.calories ?? null,
      proteins: input.proteins ?? null,
      carbs: input.carbs ?? null,
      fats: input.fats ?? null,
      logged_at: input.logged_at ?? (/* @__PURE__ */ new Date()).toISOString()
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Aliment enregistr\xE9 (id: ${data.id}).` }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/tools/list-symptoms.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_symptoms_default = defineTool3({
  name: "list_symptom_logs",
  title: "Lister les sympt\xF4mes enregistr\xE9s",
  description: "Retourne l'historique des sympt\xF4mes m\xE9nopausiques (bouff\xE9es de chaleur, fatigue, insomnie, sautes d'humeur, scores personnalis\xE9s) sur une plage de dates.",
  inputSchema: {
    from: z3.string().describe("Date de d\xE9but YYYY-MM-DD.").optional(),
    to: z3.string().describe("Date de fin YYYY-MM-DD.").optional(),
    limit: z3.number().int().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("symptom_logs").select(
      "id, logged_at, bouffees_chaleur, fatigue, insomnie, sautes_humeur, selected_symptoms, symptom_scores, notes"
    ).order("logged_at", { ascending: false }).limit(limit ?? 60);
    if (from) q = q.gte("logged_at", from);
    if (to) q = q.lte("logged_at", to + "T23:59:59");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { symptoms: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_journal_entries_default = defineTool4({
  name: "list_journal_entries",
  title: "Lister les notes du journal personnel",
  description: "Retourne les entr\xE9es du journal personnel de l'utilisatrice.",
  inputSchema: {
    from: z4.string().optional(),
    to: z4.string().optional(),
    limit: z4.number().int().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("journal_entries").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (from) q = q.gte("created_at", from);
    if (to) q = q.lte("created_at", to + "T23:59:59");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool5({
  name: "get_profile",
  title: "Voir mon profil NutriM\xE9no",
  description: "Retourne le profil nutritionnel de l'utilisatrice (\xE2ge, phase de m\xE9nopause, objectifs, restrictions).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data, error } = await sb.from("profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rxiayqubsaufrxbcmspm";
var mcp_default = defineMcp({
  name: "nutrimeno-mcp",
  title: "NutriM\xE9no",
  version: "0.1.0",
  instructions: "Outils pour NutriM\xE9no, l'app de nutrition personnalis\xE9e pour la m\xE9nopause. Permet \xE0 un assistant IA de lire le profil, les repas logg\xE9s, les sympt\xF4mes et le journal personnel de l'utilisatrice, et d'ajouter des aliments \xE0 son journal. Toutes les donn\xE9es sont limit\xE9es \xE0 l'utilisatrice connect\xE9e.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_food_logs_default, log_food_default, list_symptoms_default, list_journal_entries_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
